version: '2'
services:
    mongodb:
        image: mongo
        volumes:
            - ./volumes/mongodata:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
        ports:
            - '127.0.0.1:27017:27017'
        networks:
            - ebm

    redis:
        image: redis:5.0.5-alpine
        ports:
            - '127.0.0.1:6379:6379'
        volumes:
            - ./volumes/redis_data:/data
        networks:
            - ebm

networks:
    ebm:
        driver: bridge
